# Generated by Django 2.2.6 on 2019-10-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='rated',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
