# Generated by Django 2.2.6 on 2019-10-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191016_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='rated',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
